### ISSUE TITLE
AttributeError: move_to requires a WebElement

### ISSUE THREAD

**Issue by hackazer** [teal33t/captcha_bypass#5]
When tried to be used on login page that the recaptcha is already there (just need to click the recaptcha button without needing to wait for the recaptcha to load up as per in your medium page). error showed up.

**AttributeError: move_to requires a WebElement**

![image](https://user-images.githubusercontent.com/9864359/96962699-8b533900-1531-11eb-9075-59cdebd9331e.png)

![image](https://user-images.githubusercontent.com/9864359/96962153-6e6a3600-1530-11eb-8e50-4c222e0cffd8.png)

**Comment by teal33t** [comment]
@hackazer  you should use `move_to_element`
